### ISSUE TITLE
Client sends display IP address in host order

### ISSUE THREAD

**Issue by rakslice** [astrand/xdmcpc#1]
My test setup
- XDMCP client host is little-endian (Intel Celeron N3160 running Ubuntu 16.04 in a chroot under ChomeOS)
- XDMCP server host is little-endian (Intel Core i7-2600k running Solaris 8 Intel in a VirtualBox VM under Windows 10); the XDMCP server software is Sun's display manager `dtlogin`
- DISPLAY value in the environment where `xdmcpc` is running has an IP address `192.168.2.158:1`

On the client side, I run:
`xdmcpc -v -d2 -A/var/tmp/authfile1 192.168.2.133`
and eventually it fails and the session closes. 
In the server's `/var/dt/Xerrors` log, I see:
```
error (pid 682): Hung in XOpenDisplay(158.2.168.192:1) attempt #0, aborting.
```
The IP address in the message is reversed.

I don't know where the mistake is per se, but if I add an
```addr = htonl(addr);```
after the 
```if (get_addr(dpyhost, &addr, &cal[0]) != 1) { ... }```
block in `xdmcp.c`, so that the value is swapped before it is used in the `XDMCP_STATE_START_CONNECTION` message, the XDMCP session is established properly.

**Comment by rakslice** [comment]
Offtopic:

Cheers on the standalone xdmcp client, this is very handy.  

The `crouton` chroot manager on ChromeOS can use the stock `Xorg` in Ubuntu but needs to do some magic with `xrandr` to get it to work, and the built-in `Xorg` XDMCP support prevents `xrandr` from connecting, so is basically useless in this scenario. With a standalone XDMCP client, I can literally run it through `xinit` and take advantage of the glue that `crouton` has already provided in there -- this is the perfect illustration why XDMCP support should be modular.

I can't get the MIT-MAGIC-COOKIE auth through `xdmcpc` to work, but there is no obvious endianness problem there, and I haven't narrowed down the problem further -- for my needs it's fine to just authorize the entire host first instead.

**Comment by rakslice** [comment]
Whoops, I actually mixed up my systems... the server I was connecting to is not Solaris 10 on an Ultra 10, but Solaris 8 on x86... maybe the endianness problem is a porting issue on the server side.

**Comment by rakslice** [comment]
Okay, I've done what I should have done in the first place: looked at the network traffic.

The display address in the XDMCP Request that xdmcpc was sending is definitely in host order, although it is also being padded with 4 trailing zero bytes for some reason.

```01 00 08 9e 02 a8 c0 00 00 00 00```

[xdmcpc_4593b12_to_sol8intel.pcap.gz](https://github.com/astrand/xdmcpc/files/2153288/xdmcpc_4593b12_to_sol8intel.pcap.gz)

for comparison, in place of that Xnest (which works) has:

```01 00 04 c0 a8 02 9e```

[Xnest_to_sol8intel.pcap.gz](https://github.com/astrand/xdmcpc/files/2153289/Xnest_to_sol8intel.pcap.gz)

**Comment by astrand** [comment]
Thanks!
